function out1 = final_opt_time_stop(v0,a0,sf)
%FINAL_OPT_TIME_STOP
%    OUT1 = FINAL_OPT_TIME_STOP(V0,A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Dec-2022 19:00:01

out1 = (sf.*1.0e+1)./(v0.*2.0+sqrt(a0.*sf.*5.0+v0.^2.*4.0));
